poem-web/poem

- poem/src/middleware/cors.rs
Hello! Really liking this library so far, especially the OpenAPI integration. I found a small bug in the CORS middleware:
Allowed origins should be returned in Access-Control-Allow-Origin for preflight responses to work correctly.
> Fix CORS Preflight response

- .github/workflows/ci.yml
- .github/workflows/code-coverage.yml
Setup Swatinem/rust-cache@v1
If the cache is hit, it can reduce the ci time by roughly 8 minutes.
Signed-off-by: Chojan Shang <psiace@outlook.com>
> Add basic cache for ci

- docs/book.toml
I was just poking around the [book](https://poem.rs/openapi/custom_request.html) and found that pushing the play button results in a compilation error as the default edition is 2015 (which doesn't have `async`). I _think_ this will fix it based on the [mdBook book](https://rust-lang.github.io/mdBook/format/configuration/general.html).
> Fix playground in book

- docs/en/src/openapi/quickstart.md
- docs/zh-CN/src/openapi/quickstart.md
Personally, the document itself is a very important piece of using OpenAPI. Including it in the Quickstart will hopefully make adoption that tiny bit smoother for new users.
It may be better to put it on its own line like the SwaggerUI with a comment, but I don't know Chinese and figure it's better to keep both up to date 😅
> Include route to openapi.json in Quickstart.

- poem-openapi-derive/src/api.rs
- poem-openapi/src/registry/ser.rs
- poem-openapi/tests/security_scheme.rs
This is mostly because my generator currently interprets the presence of security as a reason to require security (even if it's empty). Really I oughta fix my generator but it looked like security (on the path at least) was intended to be omitted due to [this line](https://github.com/poem-web/poem/blob/04654b8ffd42a7240a08a8059b31c7a3d1d2ef99/poem-openapi/src/registry/mod.rs#L423), so I figured the change would be welcome.
By the way I very rarely touch macros so if there's a more clever way to do this let me know. Thanks!!
> Omit empty security schemas from OpenAPI document.

- README.md
CI is currently failing, you can merge this in so that it can re-run and hopefully publish to cargo.
> Correct link to `poem-dbsession`

- poem-openapi/src/docs/openapi.md
The specific goal was to add an example of the path param syntax which I had a bit of trouble discovering. ~~I feel like these examples should be tested somehow to stay in sync but not sure the best way to do that.~~
By the way, what happened to the mdbook that used to be around? I found that really helpful 😅 and there's a way in mdbook to pull in examples from docstrings, so the examples are tested, docstrings are present when checking out the docs.rs entry (e.g., where I was originally looking for `#[OpenApi]` docs before my last PR), and everything is in sync.
> docs: Add examples to some OpenApi and Operation attributes.

- poem-openapi/src/types/external/btreeset.rs
- poem-openapi/src/types/external/hashset.rs
- poem-openapi/src/types/external/mod.rs
This adds support for HashSet and BTreeSet types to OpenAPI for the array types.
It does not add a custom format or do anything clever.
> Add HashSet and BTreeSet support to OpenAPI

- poem-openapi/Cargo.toml
- poem-openapi/src/types/external/mod.rs
- poem-openapi/src/types/external/url.rs
While `Uri` support exists, the popular crate `Url` is not supported. This implements support for that derived from the `Uri` implementation.
> Add Url support to OpenAPI

- poem-openapi/src/error.rs
- poem-openapi/tests/api.rs
- poem/src/error.rs
Now, if the `ContentType` is incorrect, the server returns a `405` error, but according to the specification, `415` is more appropriate. 
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/415
https://datatracker.ietf.org/doc/html/rfc7231#section-6.5.13
In addition, such a response code is used in most web frameworks 🤔
> fix: unsupported media-type (415) instead of method not allowed (405)

- poem/src/middleware/tracing_mw.rs
Hey there! Thanks for making such a great library!
I recently got started with Poem and needed to customize the default `Tracing` middleware, so I looked at its implementation and noticed it was using `SystemTime`.
I thought switching to `Instant` would make the code a bit simpler while preserving the intent, but happy to close if you disagree. Thanks!
> Replace `SystemTime` with `Instant`

- poem-openapi/Cargo.toml
- poem-openapi/README.md
- poem-openapi/src/lib.rs
- poem-openapi/src/types/external/bson.rs
- poem-openapi/src/types/external/mod.rs
This adds a `Type` impl for `bson`'s `ObjectId` type. 
Some feedback would be greatly appreciated - I'm not sure what `fn raw_element_iter` is supposed to do, or that the name I've given the schema is good.
> Integrate poem-openapi with `bson::oid::ObjectId`

- poem-openapi/src/types/external/decimal.rs
Normalize decimals in OpenAPI-responses so for example 0.3 gets returned as "0.3" instead of "0.3000000".
> Openapi: Normalize decimals in responses

- poem/src/error.rs
Fixes what I believe are typos in `poem/src/error.ts` These two functions seem to mention the `503` error code specifically but I believe it is incorrect, and it creates errors with the provided status codes.
> Fix error.ts typo

- poem-openapi/Cargo.toml
- poem-openapi/src/payload/form.rs
- poem-openapi/src/payload/mod.rs
It only works for a urlencoded body. This works the same as poem's `Form<T>`
This introduces an extra dependency on serde_urlencoded as well, since poem does not reexport it.
I am not 100% sure that this should be in the `payload` module, since you can't really give a form response. 
This is related to #241, even though it does not solve that issue it is enough for me to no longer require that one solved.
> Add the ability for parameters to come from urlencoded forms.

- poem-openapi-derive/Cargo.toml
Previously we locked the version of indexmap to `1.6.2` to help a user deal with https://github.com/tkaitchuck/aHash/issues/95 (see https://github.com/poem-web/poem/issues/258). Unfortunately this means that anyone who has up to date dependencies might run into issues preventing them from using this crate, because the deps require `> 1.8`.
For example:
```
$ cargo run
Blocking waiting for file lock on package cache
Updating git repository `https://github.com/banool/poem`
Updating crates.io index
error: failed to select a version for `indexmap`.
... required by package `guppy v0.13.0`
... which satisfies dependency `guppy = "^0.13.0"` (locked to 0.13.0) of package `determinator v0.8.0`
... which satisfies dependency `determinator = "^0.8.0"` (locked to 0.8.0) of package `x v0.1.0 …
```
> Advance version of indexmap for openapi-derive

- examples/openapi/union/src/main.rs
- poem-openapi/Cargo.toml
- poem-openapi/src/openapi.rs
This is a nice convenience to offer users who need their spec as YAML, rather forcing them to take the JSON and convert it to YAML (which can be unreliable).
```
cd examples/openapi/union
cargo run
```
Now go visit http://127.0.01:3000/docs/spec_yaml and see that it returns a YAML version of the spec.
I likely need to add some unit tests for this, but first I'll wait for the maintainers to give the green tick on this idea in general.
Thanks!
> Add support for returning OpenAPI spec as YAML

- poem-openapi/Cargo.toml
- poem-openapi/src/lib.rs
- poem-openapi/src/types/external/humantime.rs
- poem-openapi/src/types/external/mod.rs
I would love to be able to represent durations as part of the OpenAPI spec. As it is now you have to just make a field like "duration_secs" and trust the user will pass the value in as seconds. With this, you can instead get the rich parsing from humantime.
Naturally I made this an optional feature.
Tested with:
```
cargo test --features humantime
```
I see the other external types largely don't have tests so I didn't write specific tests for this either.
> Add optional support for humantime Duration in poem Object

- poem-openapi-derive/src/union.rs
- poem-openapi/tests/union.rs
In the OpenAPI specification, it states that these are the only valid characters for a component name:
```
A..Z a..z 0..9 . _ -
```
From https://swagger.io/docs/specification/components/.
As such, Poem doesn't generate conformant component names right now. This PR changes the generation from `Parent[Child]` to `Parent_Child`. I feel this is the best option, `-` and `.` are generally special characters in some languages and that would make the client generation less predictable.
We should bump the minor version for this one since it's a breaking change.
> Use Parent_Child instead of Parent[Child] for generated intermediate type

- poem-openapi/src/error.rs
All the other parse errors return 400, but this one returns 404. This PR makes it conform to the other parse errors.
> Return 400 when parsing path fails, not 404

- poem-openapi/Cargo.toml
This is a breaking change in the sense that the output from the YAML generator will be different. Saying that, idk if anyone uses this feature but me :p
> Update serde_yaml to 0.9.0

- poem/src/error.rs
This would be helpful to me in the function I'm writing to use with `catch_all_errors`.
> Add `has_source` function to Error

- poem/src/error.rs
- poem/src/middleware/size_limit.rs
There is a specific error code for this case, let's use it.
> Use LENGTH_REQUIRED instead of BAD_REQUEST in SizeLimit middleware

- .github/workflows/close-stale-prs-and-issues.yml
Since many issues open are without activity or features implemented this GitHub workflow will clean and close them periodically.
> Add close stale issues and PRs github workflow

- poem/src/web/cookie.rs
Right now, we cannot iterate over cookies in a cookie jar, because the `iter()` method from the inner `libcookie::CookieJar` is not exposed.
Being able to iterate over the cookie jar is useful whenever we do not know the exact names to `get()` cookies by in advance.
I therefore created this small PR to add the method to the poem API as well.
> Expose libcookie `iter()`

- poem-openapi-derive/src/api.rs
- poem-openapi-derive/src/response.rs
- poem-openapi-derive/src/response_content.rs
- poem-openapi/tests/api.rs
- poem-openapi/tests/response.rs
- poem-openapi/tests/response_content.rs
This PR fixes the issue #365, where the `actual_type` attribute is not being added to the schema registry causing the API server to crash.
> Add actual_type to schema registry

- poem/src/middleware/tracing_mw.rs
As described in title. @sunli829 thanks for you hard work! ❤️
> Fix: trace nested route with original uri

- poem/src/error.rs
When you just print an anyhow error normally, you only get the top level problem, any context is thrown out. This PR makes it print the full error context: https://docs.rs/anyhow/latest/anyhow/struct.Error.html#display-representations.
> Include full error context from anyhow errors in PoemError

- README.md
Currently, the rust version of Casbin is ready for production and we are developing the ecosystem around it. 
`poem-casbin` uses Axum web framework to build a basic middleware which can handle requests with authorization control. It can basically read username, request path, request method and send enforce request to casbin enforcer for authorization. 
I wish to add a pointer to its repository it in the showcase examples of your repository so that its accessible to the community
> feat: Request to add poem-casbin in examples of community use

- poem-dbsession/Cargo.toml
- poem-openapi/Cargo.toml
- poem/Cargo.toml
Try to fix vulnerability reported by `cargo-audit` in chrono crate, which is rooted in `time` 0.1 crate. Down below is the screenshot of the whole workspace dependencies before this modification.
This PR follows the instructions under this chrono issue discussion: https://github.com/chronotope/chrono/issues/602
I'm not quite sure if poem actually uses `alloc` or `std` feature of `chrono` crate, so I'm leaving this to repo owner to make sure, or wait until all tests pass.
> Copy workaround solution from chrono official issue discussions

- poem/src/session/server_session.rs
The previous pull request was merged too quickly. I've made some improvements. More correct fix #430.
> Even more compact packing of random bytes in session_id

- poem-openapi/src/types/external/ip.rs
- poem-openapi/src/types/external/mod.rs
Haven't tested it. Let me know if you'd like any changes.
Closes https://github.com/poem-web/poem/issues/441
> Add Ipv4Addr and Ipv6Addr openapi support

- poem-openapi/src/lib.rs
It's not work now
`poem-openapi = { version = "2.0.22", features = ["openapi-explorer"] }`
and must add another feature
`poem-openapi = { version = "2.0.22", features = ["openapi-explorer", "swagger-ui"] }`
> Add the missing feature `openapi-explorer` in `ui` mod

- poem-openapi/Cargo.toml
- poem-openapi/src/payload/yaml.rs
- poem-openapi/src/types/mod.rs
- poem/Cargo.toml
- poem/src/error.rs
- poem/src/test/request_builder.rs
- poem/src/test/response.rs
- poem/src/web/mod.rs
- poem/src/web/yaml.rs
> add yaml support

- examples/poem/auth/src/main.rs
The html was probably copy pasted from the CSRF example but the `auth` example has nothing to do with CSRF so I adjusted the html titles accordingly.
> Fix html typo in auth example

- poem-openapi/src/openapi.rs
- poem-openapi/src/registry/ser.rs
This PR addresses this [issue](https://github.com/poem-web/poem/issues/470).
@sunli829  please review and let me know if this is ok with you
> Allow optional prefix in generated spec

- examples/poem/i18n/src/main.rs
- poem/src/i18n/args.rs
I think the tuple way of mapping I18NArgs is very *poor*. For instance, when you don't know the amount of args, you must **handle each amounts**. So I implemented From\<HashMap>.
My personal use case is making a filter `translate` for tera templating:
```jsx
<h1>{{ "hello" | translate(name=name) }}</h1>
```
```rust
fn filter(&self, id: &Value, args: &HashMap<String, Value>) -> Result<Value> {
self.locale
.text_with_args(id.as_str().unwrap(), args)
.map(|str| Value::String(str))
.map_err(|err| Error::msg(err))
}
```
> Add From<HashMap> implementation for I18NArgs

- Cargo.toml
- examples/poem/tera-templating/Cargo.toml
- examples/poem/tera-templating/src/main.rs
- poem-openapi-derive/src/multipart.rs
- poem-openapi/Cargo.toml
- poem/Cargo.toml
- poem/src/middleware/tokio_metrics_mw.rs
- poem/src/session/redis_storage.rs
Related issue: https://github.com/tafia/quick-xml/issues/540
> fix: make more conflict deps to workspace, pin `quick-xml`

- poem-openapi-derive/src/object.rs
- poem-openapi/src/payload/xml.rs
- poem-openapi/src/payload/yaml.rs
- poem-openapi/tests/response.rs
- poem/src/test/request_builder.rs
- add `ParseFromYAML` & `ParseFromXML` implements for  derive macro `Object`
- fix implement errors in `ParsePayload` for and & yaml
> fix errors when parse yaml & xml request

- poem/Cargo.toml
- poem/README.md
- poem/src/listener/acme/client.rs
- poem/src/listener/mod.rs
This works to resolve CA issues in static binaries.
I added two new features:
- `acme-native-roots` which `acme` aliases for backwards compatibility.  I left `acme` in the documentation though, maybe I should replace that with `acme-native-roots`?
- `acme-webpki-roots` which selects webpki roots
I think this is similar to what other libraries do.  I thought this was clear and would provide a path for doing manual roots too in the future.  However, if you don't select either feature, there will be a compile error when building the AcmeClient.
An alternative is to have `acme-webpki-roots` be a toggle, where if it's missing native roots are used and if it's enabled native roots are disabled (and webpki roots are enabled).  This restricts it to exactly two modes however.
> Fix #500: Webpki roots

- poem/src/endpoint/static_files.rs
The default for this option was true and could not be changed.
> Allow not falling back to index file in StaticFilesEndpoint

- poem-openapi-derive/src/api.rs
- poem-openapi/tests/api.rs
This is my attempt at adding support for pattern matching in function arguments.
Example code:
```rust
#[OpenApi]
impl Api {
#[oai(path = "/test3/:user_id", method = "get")]
async fn test3(&self, Path(user_id): Path<i32>) {
assert_eq!(user_id, 7);
}
}
```
In current master this code doesn't compile ("Invalid param definition"), I updated the attribute macro code to allow it.
> Pattern matching in OpenAPI function args

- poem/src/lib.rs
- poem/src/route/mod.rs
- poem/src/route/router.rs
Right now `PathPattern` struct is not accessible. This PR makes it reachable.
Private `PathPattern` prevents users from writing their middleware that wants to rely on path patterns. Currently existing `OpenTelemetryMetrics` middleware is really a no-go for some, because of the enormous cardinality (HTTP_URL is to blame).
> Public path pattern

- poem/src/server.rs
It's currently looks a bit fragile:
It's possible to spawn new future, but parallel task will finish before spawned task is polled. 
So this check will notify waiter & stop server:
```rs
if alive_connections.fetch_sub(1, Ordering::SeqCst) == 1 {
notify.notify_one();
}
```
It's hard to test, however sometimes we're encountering `connection reset` errors on client end, while server side almost immediately logged correct graceful shutdown & server stopped (we use large enough timeout, so it's not the case)
I believe it's more reliable & safe to increase counter before spawning the task of serving.
> fix: alive connections counter for graceful shutdown

- poem/src/lib.rs
Trivial doc change to add `test` to the list of optional crate features.
I found helpful examples for usage of `poem::test::TestClient` when making my first poem endpoint tests but it wasn't obvious I needed to enable the `test` feature since it wasn't included in this list.
> Trivial doc change to add `test` to the list of optional

- Cargo.toml
Seems like tracing changed public interface in https://github.com/tokio-rs/tracing/pull/2212
And poem is using the new interface already, so it fails with tracing <= 0.1.35.
```
Checking poem v1.3.55 (https://github.com/poem-web/poem.git?branch=master#9941b489)
error[E0277]: the size for values of type `str` cannot be known at compilation time
--> /Users/stepantubanov/.cargo/git/checkouts/poem-5d35782906f249bc/9941b48/poem/src/middleware/tracing_mw.rs:50:41
|
50   |             span.record("path_pattern", path_pattern.0.as_ref());
|                  ------                 ^^^^^^^^^^^^^^^^^^^^^^^ doesn't have a size known at compile-time
|                  |
|                  required by a bound introduced by this call
|
= help: the trait `Sized` is not implemented for `str`
note: …
```
> fix: use compatible tracing version

- poem/src/test/client.rs
This pull request adds a new function, upsert_default_header(), to the TestClient struct. This function allows users to update or insert a default header value for each request, making it easier to rotate the Authorization header with different access tokens during testing.
Add upsert_default_header() function to TestClient struct
Include example usage of upsert_default_header() in comments
While testing endpoints with User Auth I want to be able to dynamically change the Auth Header to simulate different users with different roles/access tokens.
```rust
pub async fn set_auth(&mut self, user_id: i32, auth_role: AuthRole) {
let (access_token, _) =
AuthController::create_login_creds(&self.database, &self.secret, user_id, auth_role)
.await
.unwrap();
self.test_client …
```
> feat: upsert default_headers to dynamically change while testing

- poem-openapi-derive/src/union.rs
Clippy with default settings complains about this in crates using the derive(Union).
```
> cargo clippy
[...]
warning: matching on `Some` with `ok()` is redundant
--> path_to_my_api/mod.rs:55:10
|
55 | #[derive(Union)]
|          ^^^^^
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#match_result_ok
= note: `#[warn(clippy::match_result_ok)]` on by default
= note: this warning originates in the derive macro `Union` (in Nightly builds, run with -Z macro-backtrace for more info)
```
> Remove unnecessary ok() from openapi-derive to make clippy happy

- poem-grpc/src/client.rs
Request method for GRPC requests changed to POST.
As per spec:
https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md
Some http proxies trim the body of a GET request it result in an error.
Also some servers might only accept a GET request.
> poem-grpc: request method should be post

- poem-openapi-derive/src/api.rs
- poem-openapi-derive/src/webhook.rs
- poem-openapi/src/base.rs
Hi,
we have a configuration Parameter that is dependent on both the Authorization header, as well as a parameter Value.
This PR implements an additional ApiExtractorType that allows injecting both a SecurityScheme as well as a Parameter into an OpenAPI-Spec simultanously.
> Allow ApiExtractor to provide SecurityScheme and Parameter simultaneously

- poem-openapi/README.md
The URLs were wrong.
Additionally, I couldn't get `cargo run --example hello_world` to work in either the root or the `poem-openapi/` directory, but maybe that's my version of `cargo` or something.
> (Trivial) fix example curl commands in the README.md

- poem-openapi/src/lib.rs
For some reason, this feature wasn't in the doc comment, but was in the README.md
> Update lib.rs to include openapi-explorer

- poem-openapi/Cargo.toml
- poem-openapi/README.md
- poem-openapi/src/lib.rs
- poem-openapi/src/types/external/floats.rs
cargo.toml：
```
...
serde_json = { version = "1.0.104", features = ["arbitrary_precision"] }
```
test code：
```
use poem::{listener::TcpListener, Route, Server};
use poem::Result;
use poem_openapi::{payload::Json, ApiResponse, OpenApi, OpenApiService};
struct Api;
#[derive(ApiResponse)]
enum TestResponse {
#[oai(status = 200)]
Ok(Json<Vec<f32>>),
}
#[OpenApi]
impl Api {
#[oai(path = "/hello", method = "get")]
async fn index(&self) -> Result<TestResponse> {
let test_arr = vec![32.1, 32.2];
Ok(TestResponse::Ok(Json(test_arr)))
}
}
#[tokio::main]
async fn main() -> Result<(), std::io::Error> {
if std::env::var_os("RUST_LOG").is_none() {
std::env::set_var("RUST_LOG", "poem=debug");
}
tracing_subscriber::fmt::init();
let api_service =
OpenApiService::new(Api, "Hello World", …
```
> fix: Json(Object) is not correct when f32 type in Object, when project use serde_json's "arbitrary_precision" feature.

- poem-openapi/src/ui/swagger_ui/mod.rs
Addressing https://github.com/poem-web/poem/issues/660
> Addressing misplaced `<html>` tag in swagger template (#660)

- poem-openapi/src/types/external/hashmap.rs
- poem-openapi/src/types/external/hashset.rs
- poem-openapi/src/validation/max_properties.rs
- poem-openapi/src/validation/min_properties.rs
- poem/src/i18n/args.rs
In this pull request, I added a generic parameter to all HashMap traits to support the custom Hash function. In my case, I wanted to add support for `ahash`.
> Support for custom hash functions for HashMap

- poem-openapi/src/validation/max_length.rs
- poem-openapi/src/validation/min_length.rs
- poem-openapi/tests/validation.rs
Currently in the poem's OpenAPI module, derived **maxLength** and **minLength** validators use `str::len()` method, which counts UTF-8 bytes, not Unicode characters in string. While **JSON Schema** spec defines **maxLength** and **minLength** for number of characters.
This pull request fixes that, also adding extra couple unit tests to better cover edge cases.
> count string length correctly in OpenAPI validators

- poem/Cargo.toml
- poem/src/listener/unix.rs
This helps avoid having to set permissions and ownership on the socket after it is created.
Thank you!
> added permissions and owner to UnixListener

- poem-openapi/Cargo.toml
- poem-openapi/README.md
- poem-openapi/src/types/external/geo.rs
- poem-openapi/src/types/external/mod.rs
Implements `Type`, `ParseFromJson` and `ToJson` on GeoJSON geometries by integrating with `geo-types` and `geojson`. 
Partially solves: https://github.com/poem-web/poem/issues/585
I'm a bit unsure if the dependencies have been correctly added in `Cargo.toml`, given that I was unable to find any mention of the other features there (`uuid`, `chorno`, `url` etc.).
The only missing geometry I haven't yet implemented is [`GeometryCollection`](https://datatracker.ietf.org/doc/html/rfc7946#appendix-A.7). Perhaps an issue could be opened to implement it, but I could also (if wished for) add it here.
> Initial GeoJSON support

- examples/openapi/combined-apis/Readme.md
Closes #714  
Documentation on how to merge API specs has been added with proper examples in Rust language. The documentation features a dual approach: a brief and straightforward section for quick reference by experienced users and a detailed, beginner-friendly section with explanations and examples in Rust on how to merge API specifications.
> added documentation on how to merge API specs

- poem/src/web/websocket/extractor.rs
The RFC [allows the use of](https://datatracker.ietf.org/doc/html/rfc6455#section-11.2) `WebSocket` which some frameworks follow, e.g. [autobahn](https://github.com/crossbario/autobahn-python/issues/1489#issuecomment-861391942).
> allow WebSocket casing for upgrade header

- poem-openapi/src/types/external/humantime.rs
- poem-openapi/src/types/external/humantime_wrapper.rs
- poem-openapi/src/types/external/mod.rs
1. You can't derive `serde::{Deserialize, Serialize}` together with `poem_openapi::Object` with the current implementation, but I expect that's what most people would want to do. If you want to derive `Object` for a struct, chances are that you will use it for an API request or response, so you will also need to derive serde, but at the moment that's not possible
2. `humantime` and `humantime_serde` themselves prefer using `std::time::Duration` instead of the wrapper type `humantime::Duration`, so it makes more sense to make poem work with it too
Recently I wanted to make a struct that derived `serde::{Deserialize, Serialize}` as well as `poem_openapi::Object`. This struct had to have one `Duration` field which is parsed as human-readable strings, like `15s` or `5m`. Unfortunately that's …
> impl `Type` for `std::time::Duration` instead of only `humantime::Duration`

- poem-openapi-derive/src/api.rs
- poem-openapi-derive/src/common_args.rs
- poem-openapi/src/base.rs
- poem-openapi/tests/operation_param.rs
```rs
struct Api;
fn hello_world() -> String { String::from("Hello World") }
#[OpenApi]
impl Api {
#[oai(path = "/", method = "get")]
async fn get(
&self,
#[oai(example = "hello_world")] name: Query<String>,
) -> PlainText(String) {
PlainText(name.0)
}
}
```
> feat(openapi): added example value support for param/schema

- Cargo.toml
- README.md
- poem-grpc/README.md
- poem-lambda/README.md
- poem-openapi/README.md
- poem/README.md
Fixes https://github.com/poem-web/poem/issues/732 which is still relevant and could be easily reproducible.
Bumped `rust-version` in `Cargo.toml` file to `1.74` version, look https://github.com/rust-lang/rust/pull/115453.
> Bumping the minimal version of Rust

- poem/Cargo.toml
- poem/src/listener/rustls.rs
- poem/src/web/cookie.rs
cloned() method see
https://rust-lang.github.io/rust-clippy/master/index.html#/map_clone
> update cookie to 0.18, use cloned() method

- poem-openapi-derive/src/object.rs
- poem-openapi/tests/object.rs
Heads up: I did not run all tests locally as the dependencies don't properly resolve without installing additional stuff, but the 'object' tests run fine (if you specify the `time` dependency).
I fully understand if you don't want to merge this in the public version, as it does not come with safety features and allows the consumer of the library to violate the generated OAI spec (see comment in tests).
Also I didn't figure out where to put the documentation, so if you point me to it I will still add that.
closes #585 as far as I can tell.
> Adding `serialize_with` and `deserialize_with` attributes to struct fields

- poem/src/listener/rustls.rs
move tle key reader out from loop to avoid infinity loop
https://github.com/poem-web/poem/issues/762
> Fix entering infinite loop when parsing a wrong tls key (#762).

- examples/poem/opentelemetry-jaeger/Cargo.toml
- examples/poem/opentelemetry-jaeger/README.md
- examples/poem/opentelemetry-jaeger/src/client.rs
- examples/poem/opentelemetry-jaeger/src/server1.rs
- examples/poem/opentelemetry-jaeger/src/server2.rs
Jaeger has been compatibile with OTLP for over 2 years. We want to encourage usage of OTLP exporter.
https://github.com/open-telemetry/opentelemetry-rust/issues/995
> Update opentelemetry-jaeger to use OTLP

- examples/poem/local-server-with-browser/src/main.rs
`open::that` can block, for example when `firefox` is the default browser
on Linux and no instance of `firefox` is running.
-------------
Perhaps `tokio::spawn_blocking` with `open::that` would be better in terms of error handling than using `that_detached`. The latter does not report an error if the browser exits with an error code. OTOH, with `open::that`, killing the server might kill the browser...
> Fixup to e3b2201f: prevent open::that from blocking, fix a typo, minor code simplification

- poem/src/server.rs
It was removed after switch to `hyper 1.x` ([commit](https://github.com/poem-web/poem/commit/0b6ca89be9636472b25f3677dc957fe098f72fab)) for some reason
Is there any reason? Because it seems to broke the logic (encountered issues after upgrade)
<details>
<summary> The changes affected the behavior </summary>
```patch
-    let mut conn = Http::new()
-        .serve_connection(socket, service)
-        .with_upgrades();
+    let builder = auto::Builder::new(hyper_util::rt::TokioExecutor::new());
+    let conn =
+        builder.serve_connection_with_upgrades(hyper_util::rt::TokioIo::new(socket), service);
+    futures_util::pin_mut!(conn);
tokio::select! {
-        _ = &mut conn => {
+        _ = conn => {
// Connection completed successfully.
return;
},
@@ -366,10 +368,4 @@
}
_ = …
```
> fix: graceful shutdown after switch to `hyper 1.x`

- examples/poem/opentelemetry-jaeger/Cargo.toml
- poem/CHANGELOG.md
- poem/Cargo.toml
- poem/src/middleware/opentelemetry_metrics.rs
- poem/src/middleware/opentelemetry_tracing.rs
Here's a PR to upgrade the OpenTelemetry dependencies to the 0.22 release series.
`opentelemetry-semantic-conventions` had [a breaking change](https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry-semantic-conventions/CHANGELOG.md#v0140), so I had to make a few code changes in addition to bumping the crates.
> update opentelemetry to v0.22.x

- poem/src/server.rs
This PR just makes the behavior more reliable and kinda simplified, also addresses #661 (was able to repro manually and couldn't after the fix)
The possible race condition:
- `notify_waiters()` will notify only already registered waiters
Thus, if it's called after
```rust
drop(acceptor);
if alive_connections.load(Ordering::Acquire) > 0 {
```
But before `notify.notified()` - it might be never notified.
> fix: possible race condition during graceful shutdown

- poem-grpc/src/reflection.rs
cargo build warning:
```
11 |   use crate::{include_file_descriptor_set, Code, Request, Response, Service, Status, Streaming};
|               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
::: /Users/gerald/test/rust/poem/poem-grpc/src/macros.rs:11:1
|
11 | / macro_rules! include_file_descriptor_set {
12 | |     ($package: tt) => {
13 | |         include_bytes!(concat!(env!("OUT_DIR"), concat!("/", $package)))
14 | |     };
15 | | }
| |_- the item `include_file_descriptor_set` is already defined here
|
= note: `#[warn(unused_imports)]` on by default
```
> delete imported redundantly

- poem/src/error.rs
Fixed an issue of missing `Content-Type` header for the `ResponseError` types:
- Fixed a default implementation of the `ResponseError::as_response` fn
- Fixed an implementation of the  `StaticFileError::as_response` fn
> Fix error response builder, missing `Content-Type` header

- poem-openapi-derive/src/union.rs
- poem-openapi/tests/union.rs
This specifies the discriminator property of the discriminated union as a string literal. As OpenApi doesn't support string literals its common practice to define a literal as an enum of one option. (reference: https://github.com/OAI/OpenAPI-Specification/issues/1313#issuecomment-366988466)
This helps with code generators as it generates a type-safe discriminated union. Following is a Typescript example.
With enum defined:
```ts
ex: 
type Animal =
| { type: 'Dog', bark: string }
| { type: 'Cat', name: string }
```
Without enum defined ("type" looses its literals):
```ts
ex: 
type Animal =
| { type: string, bark: string }
| { type: string, name: string }
```
> Add enum_items to discriminated union

- examples/poem/requestid/Cargo.toml
- examples/poem/requestid/src/main.rs
- poem/Cargo.toml
- poem/src/middleware/mod.rs
- poem/src/middleware/requestid.rs
- poem/src/middleware/tracing_mw.rs
This PR introduces a feature-gated `RequestId` middleware that associates an unique ID with each incoming request. `ReqId` can be extracted in request handlers and returned as a response (e.g. for error pages). Each response contains a header with the ID (default name: `x-request-id` but the header name is configurable).
The `Tracing` middleware was made aware of the request ID and adds it to the request span (for this to work, the order of the middlewares is important. `Tracing` must be applied _before_ `RequestId`.
If `ReuseId::Use` is set, the middleware will propagate the request ID from an incoming request. If the request contained an `x-request-id` header (or whatever header name is configured), this value will be used.
> RequestId Middleware

- poem-grpc/src/encoding.rs
When a response was big enough to be split into multiple frames, the response decoder was incorrectly checking the frame decoder for an incomplete frame before receiving the remaining bytes.
> poem-grpc: message can span multiple frame

- poem-openapi/src/types/multipart/upload.rs
Some crates, including the (Amazon S3 Crate)[https://docs.rs/aws-sdk-s3/latest/aws_sdk_s3/], expect the `File` struct directly, instead of the `impl AsyncRead`. This PR exposes this `File` struct through a getter function.
> Expose Poem-OpenApi Upload File struct

- examples/poem/opentelemetry-jaeger/Cargo.toml
- poem/CHANGELOG.md
- poem/Cargo.toml
Here's a PR to upgrade the [OpenTelemetry dependencies](https://github.com/open-telemetry/opentelemetry-rust) to the 0.23 release series. The breaking changes do not seem to affect Poem this time.
> update opentelemetry to v0.23.x

- poem/src/endpoint/prometheus_exporter.rs
The header should include the version.
https://prometheus.io/docs/instrumenting/exposition_formats/#text-based-format
https://docs.rs/prometheus/0.13.4/src/prometheus/encoder/text.rs.html#12-13
> fix(prometheus): use correct `content-type` header

- poem/src/server.rs
> fix: catch unwind for serve_connection

- poem-grpc-build/src/client.rs
- poem-grpc-build/src/server.rs
see #840
May we emit package when package name is empty?
> Fix #840: Grpc build emit package when package is empty

- poem-derive/src/lib.rs
Sometimes, [`#[derive(Default)]` uses incorrect/conservative bounds](https://github.com/rust-lang/rust/issues/26925). This PR adds a manual implementation of `Default` to the `#[handler]` proc macro.
For a concrete example of this restriction, see https://github.com/poem-web/poem/issues/845.
Fixes https://github.com/poem-web/poem/issues/845.
> Add manual `Default` implementation for `#[handler]`

- poem-openapi/tests/object.rs
When only the default features are enabled, `poem-openapi/tests/object.rs` cannot be built, as it depends on the `time`  crate, which is optional.
Adding `#[cfg(feature = "time")]` to the `read_only_with_default` test and moving `use time::OffsetDateTime;` into the test function body resolves the issue.
With out this PR, `cargo test -r` produces:
```
...
error[E0432]: unresolved import `time`
--> poem-openapi/tests/object.rs:7:5
|
7 | use time::OffsetDateTime;
|     ^^^^ help: a similar path exists: `tokio::time`
error[E0599]: the method `unwrap` exists for enum `Result<Obj, ParseError<Obj>>`, but its trait bounds were not satisfied
--> poem-openapi/tests/object.rs:411:59
|
400 |     struct Obj {
|     ---------- doesn't satisfy `read_only_with_default::Obj: Sized`
...
411 | …
```
> fix read_only_with_default test when only default features are enabled

- poem/src/endpoint/embed.rs
Close #824 
----------------
This is a simple fix of this bug, which is more suitable as a default behavior of `EmbeddedFilesEndpoint`.
Its basic logic is:
First: `let path = req.uri().path().trim_start_matches('/');`
Then if `path` is empty, and `req.original_uri().path()` does not end with '/', add '/' to the original uri path and redirect.
Otherwise, if `req.original_uri().path()` ends with '/', add `index.html` to `path` and call `EmbeddedFileEndpoint`.
Otherwise check if the file pointed to `path` exists, and if so, call `EmbeddedFileEndpoint` directly.
Otherwise, add `/index.html` and check if the file exists. If it does, add '/' to the original uri path and redirect.
Otherwise, call the `EmbeddedFileEndpoint` to return an appropriate 404.
However, in the long run, …
> Fix `EmbeddedFilesEndpoint` not working for `index.html` in subdirectories

- poem/src/middleware/csrf.rs
Added feature:
Allow to set a custom name for the csrf cookie.
Related to: #801
> feat: allow to set a custom name for the csrf cookie (#801)

- poem/src/middleware/add_data.rs
- poem/src/middleware/catch_panic.rs
- poem/src/middleware/compression.rs
- poem/src/middleware/cookie_jar_manager.rs
- poem/src/middleware/cors.rs
- poem/src/middleware/csrf.rs
- poem/src/middleware/force_https.rs
- poem/src/middleware/mod.rs
- poem/src/middleware/normalize_path.rs
- poem/src/middleware/opentelemetry_metrics.rs
- poem/src/middleware/opentelemetry_tracing.rs
- poem/src/middleware/propagate_header.rs
- poem/src/middleware/requestid.rs
- poem/src/middleware/sensitive_header.rs
- poem/src/middleware/set_header.rs
- poem/src/middleware/size_limit.rs
- poem/src/middleware/tokio_metrics_mw.rs
- poem/src/middleware/tower_compat.rs
- poem/src/middleware/tracing_mw.rs
I have noticed some grammatical errors while reading through the documentation of this crate.
This PR is intended to fix the ones I noticed while not changing what they are supposed to convey.
> Grammatical fixes in middleware docstrings

- poem/src/middleware/opentelemetry_tracing.rs
In the OpenTelemetry Tracing middleware, the path pattern is not set as an attribute. I think that's because the `PathPattern` is initialized when the request is "called". Similar to [this PR](https://github.com/poem-web/poem/pull/462), I have moved the setting of the attribute to after the request is called.
As a second change (which might be considered breaking), I am renaming the span to `:method :pattern` instead of `:method :uri`. This is recommended by OpenTelemetry: https://opentelemetry.io/docs/specs/otel/trace/api/#span.
> fix: setting path pattern in opentelemetry traces

- poem-openapi/CHANGELOG.md
- poem-openapi/src/base.rs
- poem-openapi/src/docs/enum.md
- poem-openapi/src/docs/multipart.md
- poem-openapi/src/docs/object.md
- poem-openapi/src/docs/openapi.md
- poem-openapi/src/docs/request.md
- poem-openapi/src/docs/response.md
- poem-openapi/src/docs/response_content.md
- poem-openapi/src/docs/security_scheme.md
- poem-openapi/src/docs/tags.md
- poem-openapi/src/docs/union.md
- poem-openapi/src/docs/webhook.md
- poem-openapi/src/types/mod.rs
Simple find+replace from
`a OpenAPI`
to
`an OpenAPI`
Also caught a place where the original capitalisation was `OpenApi`
> Fix grammar in "a OpenAPI"

- poem/src/web/cookie.rs
My use-case is that I had a few utilities in my workspace that returns cookies (with `cookie-rs`), but I can't use them with `poem` because the cookie jar only accepts this library's cookie wrapper. Not sure if this is the best approach, though.
> feat: implement conversion from libcookie to poem cookie

- poem-openapi-derive/src/api.rs
This fixes an issue where the doc comment description of an e.g. JSON parameter of a request would not show up in the generated API spec.
For example:
```rust
#[oai(path = "/users", method = "post", operation_id = "createUser")]
async fn create_user(
&self,
/// Parameters required to create a new user
Json(params): Json<CreateUserParams>,
)
```
should translate to:
```yaml
/users:
post:
requestBody:
description: Parameters required to create a new user
content:
application/json; charset=utf-8:
schema:
$ref: '#/components/schemas/CreateUserParams'
required: true
```
but without this change `description` is missing.
> Assign the description to the request object in OpenAPI

- poem-openapi-derive/src/object.rs
- poem-openapi/src/registry/mod.rs
I've added the ability to set nullable fields on a struct with poem_api::Object derive.
Following the spec here: https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.0.md#fixed-fields-20
Either for each individual field, with `nullable` attibute, or at the struct level with `nullable_all`.
It also solves this opened issue: https://github.com/poem-web/poem/issues/701
> Implemented nullable fields for openapi spec generation

- poem-openapi/src/payload/json.rs
Currently, it's impossible to request or respond with an optional Json body. 
Example:
``` rust
#[oai(path = "/opa", method = "get")]
pub async fn get(&self, Json(test): Json<Option<Klaboom>>) -> Json<String> {
Json("Hello, world!".to_string())
}
```
expands to openapi:
``` json
"/opa": {
"get": {
"requestBody": {
"content": {
"application/json; charset=utf-8": {
"schema": {
"$ref": "#/components/schemas/Klaboom"
}
}
},
"required": true
},
...
}
```
This PR passes the `IS_REQUIRED` field to the child `T`, which solves this.
> Pass `ParsePayload<T>::IS_REQUIRED` to `T` instead of defaulting to `…true`

- poem-openapi/src/payload/json.rs
`Json` from `poem/src/web/json.rs` derives `Default` but `Json` from `poem-openapi/src/payload/json.rs` does not.
This mr makes them both derive `Default`
> make Json from poem-openapi derive Default because Json from poem does

- poem-openapi-derive/src/common_args.rs
- poem-openapi-derive/src/response.rs
- poem-openapi/tests/api.rs
This mr adds ability to use constant as status code in `ApiResponse` macro. I found it to be extremely convenient in my codebase. It should be easy to use the same approach in other places where literal is expected.
```rust
const OK_STATUS: u16 = 200;
#[derive(ApiResponse)]
enum MyResponse {
#[oai(status = OK_STATUS)]
Ok,
}
```
> allow path in status for ApiResponse

- poem/src/middleware/csrf.rs
Without setting a Path, the UA will infer the Path from the URL path, meaning that it will take the "directory name" of a URL path (so for a response for a resource at `/index`, the path would be inferred as `/`, and for a response for `/foo/bar` it would be inferred to be `/foo/` etc.).
This is problematic with CSRF for multiple reasons:
- It causes a proliferation of CSRF cookies which pollute client-side storage.
- It breaks CSRF when requests are sent across paths. For example, if a resource at `/foo/bar` contains a form which submits to `/index`, they would be theoretically using different CSRF states.
- Poem only processes a single cookie, which means that we have to rely on the ordering specified in RFC 6265 Section 5.4. This is bad for two reasons:
1. The ordering is only a …
> Set a Path on the CSRF cookie

- poem-openapi-derive/src/api.rs
- poem-openapi-derive/src/lib.rs
- poem-openapi-derive/src/parameter_style.rs
- poem-openapi-derive/src/webhook.rs
- poem-openapi/src/base.rs
- poem-openapi/src/lib.rs
- poem-openapi/src/openapi.rs
- poem-openapi/src/registry/mod.rs
- poem-openapi/tests/api.rs
- poem-openapi/tests/webhook.rs
Allows setting the desired parameter style as documented in the [swagger documentation](https://swagger.io/docs/specification/v3_0/serialization/).
Example:
``` rust
#[oai(path = "/hello", method = "get")]
async fn index(
&self,
#[oai(style = "deep_object")] Query(input): Query<String>,
) -> PlainText<String> {
PlainText(format!("hello, world! {input}"))
}
```
This currently enables custom `ApiExtractor`s to extract several types of objects from the path, query, or headers. 
In the future, I hope to improve the default Query, Path and Header extractors to take the style into account.
> Allows passing the style of a parameter in the openapi spec.

- poem-openapi-derive/src/api.rs
- poem-openapi-derive/src/security_scheme.rs
- poem-openapi/src/base.rs
- poem-openapi/tests/security_scheme.rs
This makes it so that security schemes with a fallback:
```rust
#[derive(SecurityScheme)]
enum MySecurityScheme {
MySecuritySchemeBasic(MySecuritySchemeBasic),
#[oai(fallback)]
NoAuth,
}
```
Will be reflected in the OpenAPI schema:
```jsonc
"security": [
{
"MySecuritySchemeBasic": []
},
{} // <-- the fallback scheme
]
```
This is the correct way to define optional security schemes, according to the [official specification](https://github.com/OAI/OpenAPI-Specification/blob/d237e681c2bce77413f0dfc4278e168d6ed0edb0/versions/3.0.3.md#optional-oauth2-security) as of version `3.0.3`.
Closes https://github.com/poem-web/poem/issues/959
> feat(openapi): reflect fallback security scheme in spec

- poem-openapi/src/lib.rs
This PR adds the missing condition for mod ui in lib.rs to ensure that stoplight-elements-ui is properly included when enabled.
Previously, mod ui was only included when one of the following features was enabled:
- swagger-ui
- rapidoc
- redoc
- openapi-explorer
However, stoplight-elements-ui was missing from this condition, causing it to be excluded unless one of the other features was also enabled.
Thank you, https://github.com/poem-web/poem/pull/954?new_mergebox=true#issuecomment-2661711927
> Fix missing condition for Stoplight Elements UI

- README.md
Previously, this was showing the CI state for *any* branch, which meant that whatever CI run happened to go most recently would be the status reported by the badge. Using [the branch parameter][docs] to use only the `master` branch going forward will provide a more accurate picture to folks looking at the project.
[docs]: https://github.com/github/docs/blob/main/content/actions/monitoring-and-troubleshooting-workflows/monitoring-workflows/adding-a-workflow-status-badge.md#using-the-branch-parameter
> Update CI badge in README to show only `master`

- examples/openapi/content-type-accept/src/bcs_payload.rs
- examples/openapi/custom-payload/src/bcs_payload.rs
- poem-openapi-derive/src/response.rs
- poem-openapi/src/base.rs
- poem-openapi/src/docs/response.md
- poem-openapi/src/payload/attachment.rs
- poem-openapi/src/payload/base64_payload.rs
- poem-openapi/src/payload/binary.rs
- poem-openapi/src/payload/event_stream.rs
- poem-openapi/src/payload/html.rs
- poem-openapi/src/payload/json.rs
- poem-openapi/src/payload/plain_text.rs
- poem-openapi/src/payload/xml.rs
- poem-openapi/src/payload/yaml.rs
- poem-openapi/src/registry/mod.rs
- poem-openapi/src/registry/ser.rs
- poem-openapi/src/response/static_file.rs
- poem-openapi/tests/response.rs
- poem-openapi/tests/response_content.rs
- poem-openapi/tests/webhook.rs
This makes it possible to define a range of response codes, like this:
```rust
use poem::http::StatusCode;
use poem_openapi::{payload::PlainText, ApiResponse};
#[derive(ApiResponse)]
enum CreateUserResponse {
#[oai(status_range = "2XX")]
Ok(StatusCode, PlainText<String>),
#[oai(status_range = "4XX")]
ClientError(StatusCode),
#[oai(status_range = "5XX")]
ServerError(StatusCode),
}
```
The inner `StatusCode` will be used to set the status code of the actual response.
The range syntax is defined in the [official specification](https://github.com/OAI/OpenAPI-Specification/blob/8e3015a1c549375dd64395606cf8f991b0aabbd5/versions/3.1.1.md#patterned-fields-1) as follows:
> To define a range of response codes, this field MAY contain the uppercase wildcard character `X`. For example, `2XX` …
> Define a range of response codes

- poem-openapi/Cargo.toml
I do not use this feature, and it's the only thing that pulls in `chrono` in my project. Is it really needed for `poem-openapi` to work?
> fix(openapi): do not use `cookie` feature by default

- poem-openapi/tests/security_scheme.rs
- poem/src/endpoint/static_files.rs
- poem/src/web/static_file.rs
We had an issue where the browser would cache the `index.html` file and then request JS files that was no longer served, resulting in a 404 and the browser erroring out
I added this to my own code, but having the capability built in would (besides letting me have less code on my side) make the case discoverable for others and avoid the issue to begin with.
```rust
StaticFilesEndpoint::new(static_assets_path)
.index_file("index.html")
.fallback_to_index()
.around(|ep, req| async move {
let req_path = req.uri().path();
if req_path != "/" && req_path != "/index.html" {
return ep.call(req).await;
}
let mut resp = ep.call(req).await?;
if !resp.is_success() {
return Ok(resp);
}
resp.headers_mut()
.entry(CACHE_CONTROL)
.or_insert(HeaderValue::from_static("no-cache"));
Ok(resp)
})
```
(looking at …
> feat(static-files): allow setting `no-cache` header on index file

- poem/src/session/cookie_config.rs
- poem/src/web/cookie.rs
This commit adds the `Partitioned` option to the `CookieConfig` object in the built-in Session support of poem.
Third-party cookies may soon be restricted by Chromium-based browsers (https://goo.gle/3pc-dev-issue). These browsers require developers to use "Cookies Having Independent Partitioned State (CHIPS)" (https://developer.mozilla.org/en-US/docs/Web/Privacy/Privacy_sandbox/Partitioned_cookies), which involves adding the `Partitioned` attribute in `Set-Cookie`. As a result, developers using poem to build applications may need to use the `Partitioned` option in cookies.
> feat: add `Partitioned` option for `CookieConfig`

- poem-openapi-derive/src/newtype.rs
- poem-openapi/src/docs/newtype.md
- poem-openapi/tests/newtype.rs
Parametrizing a generic object with two different `NewType`s that have the same inner type leads to a name clash at runtime. This merge request adds a rename parameter to override the default NewType names.
```rust
#[derive(NewType)]
struct NewTypeA(String);
#[derive(NewType)]
struct NewTypeB(String);
#[derive(Debug, Clone, Object)]
pub struct Wrapper<T>
where
T: Type + ParseFromJSON + ToJSON,
{
pub id: T,
}
// name clash
assert_eq!(Wrapper::<NewTypeA>::name(), Wrapper::<NewTypeB>::name()); 
```
> Support rename in NewType

- poem-openapi-derive/src/object.rs
- poem-openapi/tests/object.rs
Fixes the generated documentation for a type like
```rust
#[derive(Object)]
struct SomeObject {
fixed: u32,
#[oai(flatten)]
items: HashMap<String, u64>
}
```
Currently, such a type shows no documentation for `items`, because `HashMap<String, ...>` only contains `additionalProperties` in the schema. This PR adds tracking of `additionalProperties` in addition to `properties` and `required` when using `flatten`.
In principle we can only support one flattened type with `additionalProperties`, but it wasn't clear to me how to enforce this, so instead this PR just keeps track of the `additionalProperties` of the LAST `flatten`-ed field.
> fix(poem-openapi): handle additional_properties correctly in flatten

- poem/Cargo.toml
> chore: bump `csrf`

- poem-openapi/src/auth/api_key.rs
- poem-openapi/src/openapi.rs
- poem-openapi/src/param/mod.rs
- poem-openapi/tests/operation_param.rs
- poem-openapi/tests/security_scheme.rs
I'm not sure why CI is happy, but running `cargo test` fails to compile on master, and presumably I broke it in https://github.com/poem-web/poem/pull/986.
With the feature gates added here, both `cargo test` and `cargo test -F cookie` passes on my machine
> fix: guard cookie features behind feature toggle

- poem-openapi/src/registry/mod.rs
- poem-openapi/tests/api.rs
Update `MetaOperationParam.style` to `skip_serializing_if = "Option::is_none"` so that `"style": null` isn't included in the serialized spec output, which isn't a valid style value.
> fix(openapi): exclude style parameter when serializing if none

- poem-openapi-derive/src/api.rs
- poem-openapi-derive/src/utils.rs
- poem-openapi/tests/api.rs
This commits add automatic renaming of path parameters in route table and param extraction.
When having two same routes with different method and different param names, it resulted in one of them returning 405 instead of firing the handler.
This fix is somewhat janky, because it checks if the extracted param type is `Path` and then it renames is to `param{i}`. There could be more edge cases down the line, but for now it passess all the tests.
Fixes: https://github.com/poem-web/poem/issues/948
Related: https://github.com/poem-web/poem/issues/429
> fix(poem-openapi-derive): Allow different path param names on same route

- poem-grpc-build/src/config.rs
Adds `compile_well_known_types` and `extern_path` methods to config
that maps to the corresponding method of `prost_build::Config`.
> poem-grpc-build: add more methods to config

- poem-openapi/src/types/external/prost_wkt_types/duration.rs
- poem-openapi/src/types/external/prost_wkt_types/mod.rs
- poem-openapi/src/types/external/prost_wkt_types/timestamp.rs
This pull request adds support for new types in `prost_wkt_types`.
> openapi: support `Duration` and `Timestamp` from `prost_wkt_types`

- poem-openapi/src/docs/webhook.md
- poem-openapi/src/registry/ser.rs
The generation of webhook metadata is not according to the specs. Here is an example of a spec compliant webhook method:
``` yaml
webhooks:
newPet:
post:
requestBody:
...
```
Whereas the current poem implementation generates this:
```yaml
webhooks:
newPet:
requestBody:
```
E.g. it omits the `method` parameter. This PR fixes that.
In addition, I also improved the documentation. Both Rapidoc and Swagger UI require a `description` to display a webhook. Descriptions are not provided as tags but as Rust docs. This behaviour is not apparent from the Webhook example code.
> Fix webhook nesting

- poem-openapi/src/validation/mod.rs
- poem/src/error.rs
- poem/src/lib.rs
- poem/src/test/json.rs
- poem/src/web/yaml.rs
While looking at the documentation on how to create your own `Error` type, I had noticed some grammatical errata. This PR fixes all errata I could find while manually looking through the codebase.
> Fix grammatical errata, typos and repetitions

- poem/Cargo.toml
On Unix target platforms, e.g. Linux, [`poem::Addr`] contains a variant `Unix(Arc<tokio::net::unix::SocketAddr>)`. The type `tokio::net::unix::SocketAddr` is only defined on Unix platforms and if the tokio feature `"net"` is enabled:
* [tokio: net/mod.rs:38](https://docs.rs/crate/tokio/1.47.1/source/src/net/mod.rs#38)
* [tokio: macros/cfg.rs:317](https://docs.rs/crate/tokio/1.47.1/source/src/macros/cfg.rs#317)
This PR makes Poem depend on tokio's feature `"net"`, so the `cfg` gate is fulfilled. Downstream users may -- [for some reason] or another -- not depend on tokio at all, which would have mitigated the error introduced in [PR #1075].
[`poem::Addr`]: <https://github.com/poem-web/poem/blob/f6e509b8c3f1a9417b5f3c3d6e2ec5ca9c99e6da/poem/src/addr.rs#L14>
[tokio: net/mod.rs:38]: …
> fix(poem): use tokio feature "net"

- poem-openapi/Cargo.toml
Resolves compilation error when time feature is enabled:
- Add "macros" feature to time dependency in Cargo.toml
- Fixes unresolved import `time::macros` error in poem-openapi
Fixes build failure when using poem-openapi with time feature enabled.
> fix(deps): add macros feature to time dependency

- examples/openapi/uniform-response/src/main.rs
- poem-openapi/src/types/external/mod.rs
- poem-openapi/src/types/external/unit.rs
Motivation
---
Implementing patterns such as uniform response, as demonstrated in `examples/openapi/uniform-response`, where a response type generic over `T` is used to return `T` in a data field is awkward when unit type is desired. For cases where there is no meaningful `T`, without being able to use `()` as `T`, one is forced to use work arounds such as `#[derive(Object)] struct Unit;` or `types::Any<()>`. These changes will allow using `()` directly for those use cases. The deserialization and serialization behavior matches the behavior of serde_json's behavior for unit types.
Modifications
---
- Add `Type`, `ParseFromJSON`, `ParseFromParameter`, `ParseFromMultipartField`, `ToJSON`, and `ToHeader` trait implementation for unit type.
- Update OpenAPI uniform response example to use …
> feat(openapi): add `Type`, `To*`, and `ParseFrom*` implementations for `unit` type

- poem/src/middleware/opentelemetry_tracing.rs
This PR removes useless attributes duplicates (should be defined in tracer), useless `to_string` that do allocate for no reason and include the error type and details.
> feat(poem): improve tracing

- poem-openapi-derive/src/union.rs
- poem-openapi/tests/union.rs
This PR enables externally tagged unions with primitive types.
Since the variant name is included in the object name, externally tagged unions can also contain primitive types.
> feat(poem-openapi): support externally tagged unions with primitive types

- poem-openapi/src/types/external/mod.rs
- poem-openapi/src/types/external/path_buf.rs
Adds Type, ParseFromJSON, ParseFromParameter, ParseFromMultipartField, ToJSON, and ToHeader trait implementations for `std::path::PathBuf` and `std::path::Path`.
> feat(openapi): add `Type`, `To*`, and `ParseFrom*` implementations for `std::path::PathBuf` and `std::path::Path`
