README.md
readme_cn.md

add `readme_cn.md` file.
updated `readme.md` file.

add: readme_cn.md

---

README.md
readme_cn.md

> fix: readme repository url.
1. 上一个pr里面的readme文件仓库地址写错了，发现了更正一下！

fix: readme repository url.

---

poem-openapi/src/types/external/bool.rs
poem-openapi/src/types/external/mod.rs

poem_openapi::Object support bool type

---

README.md

Thanks for the PR(https://github.com/datafuselabs/databend/pull/2670) from @sunli829 , we refactored our http apis to poem!

[community] add databend to poem community show case

---

poem/src/lib.rs

update and reorder features doc

---

poem/src/middleware/cors.rs

fix error: blocked by CORS policy: Reqest header failed content-type is not allowed by Access-Control-Allow-Headers in preflight

fix cors error

---

.gitignore
examples/openapi/todos/.gitignore

Just adding some ignores for files that showed up when testing poem and using Visual Code on it.

[.gitignore] Expand for .vscode and additional sqlite files

---

poem/Cargo.toml
poem/README.md
poem/src/error.rs
poem/src/lib.rs

I hope, this makes sense to you! It would make using eyre with poem much more convenient.
This is obviously trivial code mostly copied from the `anyhow` integration code.
https://github.com/poem-web/poem/issues/189

[eyre06] Integration with eyre 0.6 similarly to anyhow

---

poem-openapi/tests/api.rs
poem/src/web/json.rs
poem/src/web/mod.rs

change charset utf8 to utf-8

---

poem/src/i18n/locale.rs
poem/src/middleware/propagate_header.rs
poem/src/middleware/set_header.rs
poem/src/session/cookie_config.rs
poem/src/web/mod.rs

[WIP] remove unnecessary clone

---

examples/poem/upload/src/main.rs

Add a HTML page for `upload` example, It makes example use easier!

Add HTML template for `upload` example

---

poem/src/lib.rs

I searched the docs for the extractor listings more often then I'm willing to admit, so I'd love to add a link where I would expect it.

Documentation: Add additional link to FromRequest

---

poem/src/error.rs

Fixes #256
The same bug in Actix: https://github.com/actix/actix-web/pull/2453

Do not include a body chunk in HTTP 304 responses

---

poem/Cargo.toml
poem/src/lib.rs
poem/src/listener/mod.rs
poem/src/listener/openssl_tls.rs
poem/src/listener/tls.rs

Preliminary version of TLS listener based on openssl library (tokio-openssl and openssl).

Add openssl TLS listener.

---

poem/Cargo.toml
poem/src/body.rs
poem/src/error.rs
poem/src/test/request_builder.rs
poem/src/test/response.rs
poem/src/web/mod.rs
poem/src/web/xml.rs

Add XML content type support. #296

Add xml support

---

poem/src/middleware/compression.rs

Chose Compress algorithm with priority

---

.github/workflows/ci.yml
examples/openapi/todos/Cargo.toml
poem-dbsession/Cargo.toml

Upgrade sqlx to 0.6.0

---

examples/openapi/custom-payload/Cargo.toml
examples/openapi/custom-payload/README.md
examples/openapi/custom-payload/data.bcs
examples/openapi/custom-payload/src/bcs_payload.rs
examples/openapi/custom-payload/src/main.rs
poem-openapi/src/lib.rs
poem-openapi/src/macros.rs

To make this happen I had to make one of the helper macros public, hopefully that's okay!

Add example demonstrating how to make your own payload type

---

examples/openapi/content-type-accept/src/main.rs

Hey, I'm trying to figure out how to add headers to a custom response type. I'm trying to modify an example to demonstrate how to do this. As you can see, I'm trying many different options, but I can't figure out how to do it properly. I see in some other parts of the codebase that you wrap the custom response type with `Response`, but I would like to keep the same return type for `get`, and just inject headers somehow. 
I feel like perhaps if you derive `ApiResponse`, it should expose a function to add headers, just like with the regular `Response` object. Does that make sense? If so, I can take a look at adding support for this.

Demonstrate how to add headers to the response with a custom response type

---

poem-openapi/CHANGELOG.md
poem-openapi/src/payload/mod.rs

Closes https://github.com/poem-web/poem/issues/344

fix(openapi): expose `AttachmentType`

---

poem-lambda/Cargo.toml
poem-lambda/src/lib.rs

Just updated the lambda_http version to latest

upgrade lambda_http version to v0.6.0

---

poem/CHANGELOG.md

Fix typo in CHANGELOG

---

poem/Cargo.toml
poem/src/session/server_session.rs

Correct fix [#430](https://github.com/poem-web/poem/issues/430)

More compact packing of random bytes in session_id

---

poem/src/endpoint/static_files.rs

This adds an option in the StaticFilesEndpoint that can be used to fall back onto the index file, if the static files don't exist. This is useful for hosting SPAs, that are developed with Angular, React, etc.
Change-type: minor
Signed-off-by: Andreas Fitzek <andreas.fitzek@gmail.com>

🎨: Support fall back to the index file when serving static files

---

poem/src/listener/rustls.rs

See also https://github.com/poem-web/poem/issues/455

listener::rustls: add support for elliptic curve private keys

---

.github/dependabot.yml

Set up dependabot to keep dependencies up to date.

Setup dependabot to keep dependencies up to date

---

poem/Cargo.toml
poem/src/lib.rs
poem/src/test/form.rs
poem/src/test/mod.rs

bump `tokio-tungstenite` to `0.18.0`

---

poem/src/error.rs
poem/src/session/redis_storage.rs

Currently, it is just `InternalServerError`.

fix: export real error `RedisSessionError` for `redis-session`

---

.github/workflows/ci.yml
.github/workflows/release.yml

Try to avoid always out of limit.

ci: setup `protoc` less

---

poem-openapi/src/openapi.rs
poem-openapi/src/registry/mod.rs

chore: add Clone for `OpenApiService`

---

poem-openapi-derive/src/multipart.rs

Fixes `#[derive(Multipart)]` for struct, so it will work with `#[derive(ApiRequest)]`:
```
#[derive(ApiRequest)]
enum MyRequest {
Json(Json<Data>),
File(DataUpload),
}
#[derive(Multipart)]
struct DataUpload {
file: Upload,
}
```
MyRequest will now correctly recognize content type `multipart/form-data; boudary=--....` as part of MyRequest::File

Fixes:  the `Content-Type` requested by the client is not supported: multipart/form-data; boundary=--

---

poem/src/server.rs

fix(server): graceful shutdown of established connections

---

poem-openapi/Cargo.toml
poem-openapi/src/types/external/ip.rs

Added support for ipnet crate
Also implemented Type for IpAddr so both ipv4 or ipv6 address can be used in single field/parameter

Support for ipnet crate + IpAddr

---

poem/src/route/router.rs

Fixes a panic due to a missing `*--poem-rest` param in the `Nest<E>` endpoint. Param is missing because `percent_decode` returns an error (in `radix_tree.rs`).
I'm not completely sure if this is the right way to fix it, please let me know if it makes sense to you.
Closes #471.

fix: do not panic on bad percent encoding in nested route

---

poem/Cargo.toml

Update otel ecosystem crates as well.

Update opentelemetry to v0.21.x

---

.github/workflows/ci.yml
.github/workflows/release.yml

Added protoc dependency to poem-openapi builds in Github Actions. This is necessary for the prost-wkt-types crate to build.

Attempted to fix CI/CD for prost-wkt-types

---

poem-openapi/src/lib.rs

I am new to poem-openapi and was following the quickstart guide but the given example is no valid code as it does not have a main function.

fix quickstart example

---

poem/Cargo.toml
poem/src/listener/acme/listener.rs
poem/src/listener/rustls.rs
poem/src/listener/unix.rs

update rustls-pemfile to 2.0

---

examples/Cargo.toml
examples/poem/local-server-with-browser/Cargo.toml
examples/poem/local-server-with-browser/src/main.rs

Additionally, this demonstrates how to pick an open port, since this is often relevent for local servers (Jupyter-like applications).
Cc: https://github.com/poem-web/poem/discussions/751

Add example of starting a local server and opening a browser

---

poem/Cargo.toml
poem/src/listener/acme/jose.rs
poem/src/listener/acme/listener.rs

That fix #803 and good enough for me.

Fast fix for acme

---

poem-openapi/src/types/multipart/upload.rs
poem-openapi/tests/multipart.rs

Add AsyncSeek trait to Upload::into_async_read to allow seek operation.

feat: add AsyncSeek trait to Upload::into_async_read return type

---

poem/Cargo.toml

Missed in 11790d7f6c0efbab879ceba9f13e1f8cdf46bbfb
FWIW, can also close #863

fix: update otel semconv as well

---

poem-openapi/src/types/string_types.rs

fix host name dosc

---

poem/src/middleware/mod.rs

That allows to pass middlewares with their configuration around at application setup time without having to clone them.

Implement middleware for &T: Middleware<_>

---

poem/src/web/cookie.rs

The inline comment should explain everything, hopefully.

Respect client cookie precedence

---

poem/src/web/csrf.rs

Update crate csrf to version 0.4.2 broke the CsrfVerifier. This commit accounts for the richer error and adds new function that can propagate that information
Fixes: https://github.com/poem-web/poem/issues/950

fix(poem): Handle richer libcsrf error

---

examples/poem/opentelemetry-jaeger/Cargo.toml
examples/poem/opentelemetry-jaeger/src/client.rs
examples/poem/opentelemetry-jaeger/src/server1.rs
examples/poem/opentelemetry-jaeger/src/server2.rs
poem/Cargo.toml

They're targeting a v1 in the summer, which should reduce the churn on this dep 😀 
https://github.com/open-telemetry/opentelemetry-rust/blob/ac69af6a0aea3e2a7a7ad321496ccf3314e5bf64/docs/migration_0.28.md#notes-on-breaking-changes-and-the-path-to-10

fix: update OpenTelemetry to v0.28

---

.github/workflows/ci.yml
.github/workflows/code-coverage.yml
.github/workflows/release.yml
poem/src/listener/rustls.rs

cc @sunli829 
This refers to #985 and imporve usability.

refactor: populate default provider

---

poem/src/error.rs

chore(poem): make Error small
